# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build code
    variables:
      env: Build
    jobs:
    - job: Build
      displayName: build
      pool:
       vmImage: "ubuntu-latest"
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'manifests'
          publishLocation: 'Container'
        
  - stage: DevDeploy
    dependsOn: Build
    jobs:
      - job: DevJob1
        steps:
          - bash: echo dev job1
  - stage: QADeploy
    dependsOn: Build
    jobs:
      - job: QAJob1
        steps:
          - bash: echo QA job1
  - stage: StagingDeploy
    dependsOn: Build
    jobs:
      - job: StagingJob1
        steps:
          - bash: echo Staging job1
  - stage: ProdDeploy
    dependsOn:
     - DevDeploy
     - QADeploy
     - StagingDeploy
    jobs:
      - deployment: ProductionDeployment
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: Deploy on production environment
  
