# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: "job1"
  steps:
   - script: |
      echo Default working directory
      echo $(System.DefaultWorkingDirectory)
      echo Artifact staging directory
      echo $(build.ArtifactStagingDirectory)
      echo my first job message 2
     displayName: 'my first job'
   - task: CopyFiles@2
     inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: '**/*.yml'
         TargetFolder: '$(Build.ArtifactStagingDirectory)'
   - task: PublishBuildArtifacts@1
     inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#     echo more scripts
#   displayName: 'Run a multi-line script'
